name: cron
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
    - shell: bash
      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        DROPBOX_NYTC_PATH: ${{ secrets.DROPBOX_NYTC_PATH }}
        DROPBOX_WSJC_PATH: ${{ secrets.DROPBOX_WSJC_PATH }}
        NYT_COOKIE: ${{ secrets.NYT_COOKIE }}
      run: node main.js
